#7
from tkinter import *

root = Tk()

root.title("tk")
contactListLabel = Label(root, text="Contact List")
contactListLabel.grid(column=1, row=0)
contactListTextArea = Text(root, width=30, height=10)
contactListTextArea.grid(column=1, row=1,rowspan=7)
displayContactButton = Button(root, text="Display Contact")
displayContactButton.grid(column=1, row=8)
NewContactLabel = Label(root, text="New Contact")
NewContactLabel.grid(column=4, row=0)
firstNameLabel = Label(root,text= "First Name")
firstNameLabel.grid(column=3, row=1)
firstName = Entry(root)
firstName.grid(column=4, row=1)
lastNameLabel = Label(root,text= "Last Name")
lastNameLabel.grid(column=3, row=2)
lastName = Entry(root)
lastName.grid(column=4, row=2)
phoneLabel = Label(root,text= "Phone")
phoneLabel.grid(column=3, row=3)
phone = Entry(root)
phone.grid(column=4, row=3)
friendCheckBox = Checkbutton(root, text="Friend")
friendCheckBox.grid(column=4, row=4)
emailLabel = Label(root,text= "Email")
emailLabel.grid(column=3, row=5)
email = Entry(root)
email.grid(column=4, row=5, sticky=(W, E))
birthdayLabel = Label(root,text= "Birthday")
birthdayLabel.grid(column=3, row=6)
birthday = Entry(root)
birthday.grid(column=4, row=6)
addContactButton = Button(root, text="Add Contact")
addContactButton.grid(column=4, row=8)
lastNameSearchLabel = Label(root,text= "Last Name")
lastNameSearchLabel.grid(column=0, row=9)
lastNameSearch = Entry(root)
lastNameSearch.grid(column=1, row=9)
resultLabel = Label(root,text= "Result:")
resultLabel.grid(column=4, row=9)
last_firstLabel = Label(root,text= "Last_First")
last_firstLabel.grid(column=4, row=10)
phoneLabel = Label(root,text= "Phone")
phoneLabel.grid(column=4, row=11)
searchButton = Button(root, text="Search")
searchButton.grid(column=1, row=12)

root.mainloop()
